var express = require('express');
var router = express.Router();
var bbs = require('../controllers/bbsController')

router.get("/",bbs.getPostData)
router.get("/getLikesNum",bbs.getLikesData)
router.get("/getIsLikes",bbs.getIsLikes)
router.get("/delLikes",bbs.delLikes)
router.get("/addLikes",bbs.addLikes)
router.get("/getTargetPostData",bbs.getTargetPostData)
router.get("/getFollowNum",bbs.getFollowNum)
router.get("/getFansNum",bbs.getFansNum)
router.get("/getPostByUserID",bbs.getPostByUserID)
router.get("/follows",bbs.follows)
router.get("/getFollowState",bbs.getFollowState)
router.get("/cancleFollow",bbs.cancleFollow)
router.get("/addVisitCount",bbs.addVisitCount)
router.get("/getVisitCount",bbs.getVisitCount)
router.get('/getCollectByID',bbs.getCollectByID)
router.post("/addCollect",bbs.addCollect)
router.post("/cancelCollect",bbs.cancelCollect)
router.get("/getCollectState",bbs.getCollectState)
router.get("/getCommentCountByPostID",bbs.getCommentCountByPostID)
router.get("/getCommentData",bbs.getCommentData)
router.post("/sendPost",bbs.sendPost)
router.get("/getWonderfulPost",bbs.getWonderfulPost)
router.post("/deletePost",bbs.deletePost)
router.post("/getPostsByID",bbs.getPostsByID)
router.post("/getFocusUerInfoByUserID",bbs.getFocusUerInfoByUserID)
router.post("/getFansInfoByUserID",bbs.getFansInfoByUserID)
router.post("/getPostNumByUserID",bbs.getPostNumByUserID)
router.post("/getCollectNumByUserID",bbs.getCollectNumByUserID)
router.post("/getFollowNumByUserID",bbs.getFollowNumByUserID)
router.post("/getFansNumByUserID",bbs.getFansNumByUserID)
router.get('/getCheckPost',bbs.getCheckPost)


module.exports = router;